### PR TITLE
Enable printing of info messages from SQL server like "print 'created db'"

### PR DESCRIPTION
**Pull request by angelyordanov**
I find it useful to use PRINT in my scripts so I added this small change.

Hope you find it helpful too and merge it.

Thanks,
Angel

### CODE REVIEW

**Comment by hasankhan** [comment]
Thank you, I'll take a look at this. Can you please add unit test also?

**Comment by angelyordanov** [comment]
This looks untestable with your current test setup. It is a side effect of a request execution, as a request might or might not print an info message. So in order to test this we need to test Utils.runQuery and i didn't see any tests for it.

**Comment by angelyordanov** [comment]
I agree and I've made the changes by amending the previous commit.

**Comment by hasankhan** [comment]
Thanks

**Pull request merged**
